language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="3ff74e88-116e-4433-b969-09889018301a"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - mvn test -B

notifications:
  email:
    recipients:
      -aynuuu@gmail.ru
    on_success: never # default: change
    on_failure: always # default: always